sudo: false

language: php

php:
  - '5.5'
  - '5.6'

env:
  - MYSQL=true      REDIS=true
  - MYSQL=true      MEMCACHED=true
  - POSTGRESQL=true REDIS=true

cache:
  directories:
    - node_modules
    - vendor

services:
  - memcached
  - redis-server

install:
  - npm install
  - composer install

before_script:
  - cp -a .env.example .env
  - if [ $MYSQL ];      then bin/mysql.sh; fi
  - if [ $POSTGRESQL ]; then bin/postgresql.sh; fi
  - if [ $REDIS ];      then bin/redis.sh; fi
  - if [ $MEMCACHED ];  then bin/memcached.sh; fi
  - gulp create-tables

script: phpunit
